use actix_web::{web, HttpResponse};

#[derive(serde::Deserialize)]
pub struct FormData {
    _email: String,
    _name: String,
}

// before calling this function, actix-web invokes the from_request method for all of this
// functions input
//
// Form::from_request tries to deserialise the body of the HTTP request into the FormData struct
// provided using the rules of URL encoding (serde_urlencoded and Deserialise implementation of
// FormData generated by #[derive(serde::Deserialize)])
//
// If Form::form_request fails, return 400 BAD REQUEST, else if this function is invoked, returns
// the functions value (in this case, 200 OK)
pub async fn subscribe(_form: web::Form<FormData>) -> HttpResponse {
    HttpResponse::Ok().finish()
}
